# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/users.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'proto/users.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/users.proto\x12\x05users\"o\n\x11\x43reateUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x14\n\x0cphone_number\x18\x03 \x01(\t\x12\x11\n\tgoogle_id\x18\x04 \x01(\t\x12\x10\n\x08\x61pple_id\x18\x05 \x01(\t\"!\n\x0eGetUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"{\n\x0cUserResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x14\n\x0cphone_number\x18\x04 \x01(\t\x12\x11\n\tgoogle_id\x18\x05 \x01(\t\x12\x10\n\x08\x61pple_id\x18\x06 \x01(\t2\x81\x01\n\x0bUserService\x12;\n\nCreateUser\x12\x18.users.CreateUserRequest\x1a\x13.users.UserResponse\x12\x35\n\x07GetUser\x12\x15.users.GetUserRequest\x1a\x13.users.UserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.users_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEUSERREQUEST']._serialized_start=28
  _globals['_CREATEUSERREQUEST']._serialized_end=139
  _globals['_GETUSERREQUEST']._serialized_start=141
  _globals['_GETUSERREQUEST']._serialized_end=174
  _globals['_USERRESPONSE']._serialized_start=176
  _globals['_USERRESPONSE']._serialized_end=299
  _globals['_USERSERVICE']._serialized_start=302
  _globals['_USERSERVICE']._serialized_end=431
# @@protoc_insertion_point(module_scope)
